; PlatformIO Project Configuration File

[platformio]
default_envs = T-Dongle-S3
src_dir = src

[env:T-Dongle-S3]
platform = espressif32@6.12.0
framework = arduino
board = dongles3

build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; --- LVGL Konfiguration ---
    -DLV_CONF_INCLUDE_SIMPLE          ; Ermöglicht die einfache Einbindung der lv_conf.h
    -I src                            ; Fügt das src Verzeichnis zum Include-Pfad hinzu
    -I src/images   ; <--- NEU: Erlaubt das Einbinden der Katzen-Bilder

lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.1
    lvgl/lvgl @ ^9.1.0
    fastled/FastLED @ ^3.6.0
    bblanchon/ArduinoJson @ ^7.0.4  ; <--- NEU

[env:T-Dongle-S3-Dual]
platform = espressif32@6.12.0
framework = arduino
board = dongles3-dual

[env:T-Dongle-S3-Plus]
platform = espressif32@6.12.0
framework = arduino
board = dongles3-plus
